FROM mongo:4.4.3

#COPY ./mongo/.mongorc.js:~/.mongorc.js


# CMD mongoimport --host mongodb --db reach-engine --collection MyDummyCollection --type json --file /init.json --jsonArray

#CMD mongorestore data/dump/remap2020/